### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by acelbyte** [AJaySi/AI-Writer#115]
SyntaxError: File "C:\Program Files\Artificial Intelligence\AjaySi\AI-Writer\lib\utils\alwrity_utils.py", line 48 from lib.ai-seo_tools.on_page_seo_analyzer import analyze_onpage_seo ^ SyntaxError: invalid syntax
Traceback:
File "C:\Acelbyte\Packages\Python\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Acelbyte\Packages\Python\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "C:\Program Files\Artificial Intelligence\AjaySi\AI-Writer\alwrity.py", line 12, in <module>
    from lib.utils.alwrity_utils import (blog_from_keyword, ai_agents_team, essay_writer, ai_news_writer, ai_seo_tools,
![Screenshot (20)](https://github.com/user-attachments/assets/45979f16-de21-41f8-9c70-6be565f57fda)
![Screenshot (21)](https://github.com/user-attachments/assets/c54c8583-acea-41ae-b639-58986acacf35)

**Comment by umesh070** [comment]
Hi, @acelbyte 

Could you follow these steps to solve this issue?

1. Open the AI-writer file locally.
2. Open the "lib" file. 
3. You will find the "utils" folder in the second last option. Click ok.
4. Inside utils you will find "alwrity_utils" in the third option. click ok to open the code with Visual Studio Code
5. Go to the 48th line and change [from lib.ai-seo_tools.on_page_seo_analyzer import analyze_onpage_seo] to [from lib.ai_seo_tools.on_page_seo_analyzer import analyze_onpage_seo] and save. 

please let us know if this works for you.

**Comment by acelbyte** [comment]
done, solved thank you

**Comment by AJaySi** [comment]
@umesh070 
Thanks a lot.
I will be pushing few features with this fix, today.

@acelbyte 
Sorry for the trouble. Please close the issue.

**Comment by acelbyte** [comment]
An error occurred while saving the configuration: [Errno 13] Permission denied: 'C:\Program Files\Artificial Intelligence\AjaySi\AI-Writer\lib\workspace\alwrity_config\main_config.json'

**Comment by AJaySi** [comment]
Thats windows permission problem. You will need to change your folder permission. Basically, run alwrity.py as admin.

https://stackoverflow.com/questions/64076532/how-to-allow-a-python-script-to-make-changes-to-program-files
https://discuss.python.org/t/permissionerror-errno-13-permission-denied-python-2023/22360
