### ISSUE TITLE
Could not find a version that satifies the requirements advetools (from version: none)

### ISSUE THREAD

**Issue by xDaijobu** [AJaySi/AI-Writer#124]
---
When attempting to install the `advetools` package, I receive the following error:
```
ERROR: Could not find a version that satisfies the requirement advetools (from versions: none)
ERROR: No matching distribution found for advetools
```

**Current Python Version:** 3.12.3
---

![image](https://github.com/user-attachments/assets/f0706d1e-ba6c-4a54-93ee-190c11539c0f)
![image](https://github.com/user-attachments/assets/efa71e61-6b28-4140-b317-5de54c0fe258)

**Comment by umesh070** [comment]
Can you try using Python 3.10 or 3.11 to resolve this issue.

**Comment by AJaySi** [comment]
@xDaijobu @umesh070 

If its possible, also try on google colab: https://github.com/AJaySi/AI-Writer/wiki/Steps-to-Get-Started-on-AI%E2%80%90Writer-with-Google-Colab

We will try to improve advertools and make it work with latest versions.
As you are using venv, you can try with specific python version. I will also try to disable advertool, if its a blocker for others too.

**Comment by xDaijobu** [comment]
I’m pleased to report that it's working now after I removed advertools. Additionally, I was able to successfully deploy the project into Docker.

Thank you very much for your assistance and support throughout this process.

One more thing: could you please help me understand why the output from AI Writers is not in HTML format, even though I have set the content output to HTML? 

![image](https://github.com/user-attachments/assets/5294ae46-e76d-48bc-92ef-61adc332af64)

**Comment by AJaySi** [comment]
Ooh Looks great. Congratulations.

1). Request you for a PR for dockerfile deployment. Also, it will better if we drop advertools for now.

2). HTML output: I guess that the problem with code, I will check and fix it. Please open an issue for HTML output.

3). Kindly, keep giving feedback, we will improve upon it.

BTW: We are busy building a nextjs version of this and i will send you an invite to beta test it soon.

Thank you.

**Comment by xDaijobu** [comment]
Thank you! I've already created the PR for the Dockerfile deployment and removed advertools from the requirements. Please take a look and let me know if there are any additional changes needed.

**Comment by AJaySi** [comment]
@xDaijobu 
Request you to please close this issue. We will follow up on HTML output in #126
