### ISSUE TITLE
Content Output Format Issue - Always Produces Markdown

### ISSUE THREAD

**Issue by xDaijobu** [AJaySi/AI-Writer#126]
**Description:**
The content output format is intended to be HTML, but it consistently produces Markdown format instead, even after a successful operation.

![image](https://github.com/user-attachments/assets/5294ae46-e76d-48bc-92ef-61adc332af64)

**Steps to Reproduce:**
1. Generate content output.
2. Check the format of the resulting file.

**Expected Behavior:**
The content should be in HTML format.

**Actual Behavior:**
The content is always in Markdown format.

**Reference:**
For additional context, see [Issue #124](https://github.com/AJaySi/AI-Writer/issues/124) which discusses similar problems with content format.

**Comment by AJaySi** [comment]
@xDaijobu 
Thank you reporting this. I will fix this asap.

Regards.

**Comment by AJaySi** [comment]
@xDaijobu 
Hello. I made following changes, please review:

1). The system prompt were not getting values from main_config.
2). If serper.dev api keys are over then fallback to metaphor for web results.
3). Improve error reporting and handling.
4). Improved prompts a little bit.

**Comment by AJaySi** [comment]
No comments from reporter, closing it.
