### ISSUE TITLE
package loading is very slow

### ISSUE THREAD

**Issue by ishakdemir** [AJaySi/AI-Writer#128]
![image](https://github.com/user-attachments/assets/772b3f60-b200-42e9-ace6-71f1a32bbb1f)

Installing packages by doing pip install -r requirements.txt is progressing very slowly. The computer has been on for 2 hours.

**Comment by uniqueumesh** [comment]
Hi, @ishakdemir. I recently install the package. It won't take much time. There can be a issue in laptop or try ctrl+c and retry again.
