### ISSUE TITLE
It is too slow to run "pip install -r requirements.txt" for packages have no version. Pip have to decided dependency.

### ISSUE THREAD

**Issue by hanwayTech** [AJaySi/AI-Writer#135]
It is too slow to run "pip install -r requirements.txt" for packages have no version. Pip have to decided dependency.

**Comment by AJaySi** [comment]
https://www.google.com/search?client=ubuntu-sn&channel=fs&q=slow+pip+install+

Not really an ALwrity issue. We can of course save some seconds here and there but pip is slow and wheel maybe a better option. Also, ALwrity should support latest package versions and not stick to one.

Can you please do a pip install with specific versions and benchmark the install time against as-is ?
Thanks.
