### ISSUE TITLE
add gemini ai and openrouter api support

### ISSUE THREAD

**Issue by tukangcode** [AJaySi/AI-Writer#137]
Hi can add gemini ai api and openrouter support ? thanks

**Comment by AJaySi** [comment]
Google Gemini API is supported. You can change it from the sidebar.
I will look into openrouter.

Thanks.

**Comment by AJaySi** [comment]
@tukangcode 

As Gemini is already present and openrouter is not on the cards for us. I will close for now.
Note: We are concentrating on building a nextjs saas webapp for ALwrity and phasing out this streamlit version..
