### ISSUE TITLE
how to  edit api key setting again ? it not appear

### ISSUE THREAD

**Issue by tukangcode** [AJaySi/AI-Writer#138]
hi ! how to edit api key setting is not apper again after i submit my gemini api but forgeting other api set, are i screw and need reinstall from beginning ?

**Comment by AJaySi** [comment]
Hi @tukangcode , 
1). Once you have installed, check the options in Sidebar. This has an option of GPT provider. Choose gemini and prvide API key. 

2). Also, where you have downloaded alwrity, in that folder there is a file .env
Check this file .env and change to gemini and provide the keys.

Let me know if this helps.

**Comment by tukangcode** [comment]
thanks it work now.
