### ISSUE TITLE
OpenAI API Error 429: Insufficient Quota despite valid API key

### ISSUE THREAD

**Issue by mflisiuk** [AJaySi/AI-Writer#140]
Hi,

I am trying to use your tool with OpenAI LLM, but I am getting a 429 Error Code 'insufficient_quota'. 

**Current setup:**
- I have a valid OpenAI API key
- The same key works correctly in other tools/applications
- I've checked my OpenAI account settings and everything seems to be properly configured

**Error message:**
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Questions:**
1. Is there a specific usage limit for your tool?
2. Could there be any configuration issues specific to your implementation?
3. Are there any known workarounds or alternative settings I should try?

Any help would be appreciated!

**Comment by AJaySi** [comment]
Hello @mflisiuk 

1). ALwrity does not impose any usage restrictions. The message is from your API provider. 
2). No to both your questions 2 & 3..
3). Please recheck your AAPI keys.

**Comment by AJaySi** [comment]
User end error.
