### ISSUE TITLE
Help regarding generating blog from audio (YouTube)

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#27]
I tried to generate a blog using audio to blog (Alwrity features). I have seen different outputs (example) in the "wiki". And I am getting a different output. I have attached the output image below.  Please help regarding this issue. Thank you.

![Screenshot (4)](https://github.com/AJaySi/AI-Writer/assets/150319020/75b5e336-ab02-4354-85af-79446c656761)

**Comment by AJaySi** [comment]
Thanks for the screenshot. I will work on it today and update the code.

**Comment by AJaySi** [comment]
Hmmmm, this seems like a windows problem. 
You will need to chmod and give permissions for alwrity to create, edit and delete the its files.

Check this out: https://windowsreport.com/windows-11-python-permission-denied/

I am closing this, as its not alwrity's bug.
