### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by pixelatumente** [AJaySi/AI-Writer#29]
it's a great job, but I can't get it to work. The first versions I was able to create some posts. Although it asks me to create the web_research_reports folder. Sorry for the inconvenience. 

🔝 Top: The most popular search topics.
🚀 Rising: Topics experiencing a significant increase in search frequency since the last time period. Topics marked :pile_of_poop:'Breakout' had a tremendous surge, likely because they are new and had few prior searches.
Empty DataFrame
Columns: []
Index: []
INFO|google_trends_researcher.py:488:save_in_file| Search content saved to C:\Flota\AI-Blog-Writer\workspace\web_research_reports\los_mejores_quesos_del_mundo_2024-04-10_16-31-23
ERROR|google_trends_researcher.py:529:do_google_trends_analysis| Failed to get results from google trends related topics: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: 'charmap' codec can't encode characters in position 0-207: character maps to <undefined>
╒════╤═══════════════════════════════════════════════════╤═════════════════════════════════════════════╤══════════════════════════════════════════════════════╤════════════════════════════════════════════════╕
│    │ K📢eyword Col1                                    │ K📢eyword Col2                              │ K📢eyword Col3                                       │ K📢eyword Col4                                 │
╞════╪═══════════════════════════════════════════════════╪═════════════════════════════════════════════╪══════════════════════════════════════════════════════╪════════════════════════════════════════════════╡
│  0 │ ranking de los mejores quesos del mundo           │ los mejores quesos de todo el mundo         │ que or de                                            │ los mejores quesos del mundo 2024              │
├────┼───────────────────────────────────────────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────────────────┼────────────────────────────────────────────────┤
│  1 │ cuales son los mejores quesos del mundo           │ lista de los mejores quesos del mundo       │ el mejor queso del mundo                             │ mejores quesos del mundo lista                 │
├────┼───────────────────────────────────────────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────────────────┼────────────────────────────────────────────────┤
│  2 │ donde estan los mejores quesos del mundo          │ donde hacen los mejores quesos del mundo    │ donde se hacen los mejores quesos del mundo          │ de donde son los mejores quesos del mundo      │
├────┼───────────────────────────────────────────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────────────────┼────────────────────────────────────────────────┤
│  3 │ como vs que comparison                            │ donde producen los mejores quesos del mundo │ en que pais se producen los mejores quesos del mundo │ donde se producen los mejores quesos del mundo │
├────┼───────────────────────────────────────────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────────────────┼────────────────────────────────────────────────┤
│  4 │ en donde se producen los mejores quesos del mundo │ what is del mundo                           │ what does del mundo mean                             │          
                                      │
╘════╧═══════════════════════════════════════════════════╧═════════════════════════════════════════════╧══════════════════════════════════════════════════════╧════════════════════════════════════════════════╛
INFO|keywords_to_blog.py:73:write_blog_from_keywords| Google Trends keywords to use in the blog: ['ranking de los mejores quesos del mundo', ' los mejores quesos de todo el mundo', ' que or de', ' los mejores quesos del mundo 2024', ' cuales son los mejores quesos del mundo', ' lista de los mejores quesos del mundo', ' el mejor queso del mundo', ' mejores quesos del mundo lista', ' donde estan los mejores quesos del mundo', ' donde hacen los mejores quesos del mundo', ' donde se hacen los mejores quesos del mundo', ' de donde son los mejores quesos del mundo', ' como vs que comparison', ' donde producen los mejores quesos del mundo', ' en que pais se producen los mejores quesos del mundo', ' donde se producen los mejores quesos del mundo', ' en donde se producen los mejores quesos del mundo', ' what is del mundo',ERROR|main_text_generation.py:150:read_llm_parameters| An unexpected error occurred: 'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined>
ERROR|main_text_generation.py:55:llm_text_gen| Failed to read LLM parameters: 'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined> 
ERROR|combine_blog_and_keywords.py:30:blog_with_keywords| blog_with_keywords: Failed to get response from LLM: 'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined>
ERROR|keywords_to_blog.py:76:write_blog_from_keywords| Failed to do Google Trends Analysis:'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined>
INFO|keywords_to_blog.py:77:write_blog_from_keywords| ########### Blog Content After Google Trends Analysis:#########

INFO|keywords_to_blog.py:85:write_blog_from_keywords| Pass Final blog for blog-proof reading and *improvements.
ERROR|main_text_generation.py:150:read_llm_parameters| An unexpected error occurred: 'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined>
ERROR|main_text_generation.py:55:llm_text_gen| Failed to read LLM parameters: 'charmap' codec can't decode byte 0x9d in position 2106: character maps to <undefined> 
Failed to write blog on los mejores quesos del mundo, Error: name 'logger' is not defined

**Comment by AJaySi** [comment]
@pixelatumente @umesh070 
Sorry for the inconvenience.
I will resolve it few hours and update here.
Thanks.

**Comment by pixelatumente** [comment]
I have reinstalled Python and AI-Writer but I find it impossible to make it work. I just want to mention what is happening to me. A lot of errors. Regards!

_______________________________________________________________________

⚠️    Alert!   💥❓💥
If you know what to write, choose 'Write Blog'
If unsure, let's 'do web research' to write on
If Testing-it-out/getting-started, choose 'Blog Tools
_______________________________________________________________________

________________________________________________________________
INFO|gpt_online_researcher.py:89:do_metaphor_ai_research| Start Semantic/Neural web search with Metahpor: mejores grupos ingleses
INFO|common_utils.py:31:cfg_search_param| Reading search config params from C:\Flota\AI-Blog-Writer\main_config
ERROR|common_utils.py:87:cfg_search_param| Error: Invalid value in config file: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined> 
INFO|metaphor_basic_neural_web_search.py:121:metaphor_search_articles| Metaphor web search with Date: None and Query: mejores grupos ingleses
ERROR|metaphor_basic_neural_web_search.py:131:metaphor_search_articles| Failed in metaphor.search_and_contents: Invalid type for option 'include_domains': Expected one of [<class 'list'>], got <class 'dict'>
ERROR|metaphor_basic_neural_web_search.py:148:metaphor_search_articles| Error in Metaphor searching articles: cannot access local variable 'search_response' where it is not associated with a value
ERROR|gpt_online_researcher.py:94:do_metaphor_ai_research| Failed to do Metaphor search: cannot access local variable 'search_response' where it is not associated with a value
ERROR|keywords_to_blog.py:67:write_blog_from_keywords| Failed to do Metaphor AI search: cannot unpack non-iterable NoneType object
INFO|keywords_to_blog.py:68:write_blog_from_keywords| ######### Draft3: Blog content after Tavily AI research: #########


INFO|gpt_online_researcher.py:100:do_google_pytrends_analysis| Do Google Trends analysis for given keywords: mejores grupos ingleses
📢❗🚨 Fetching Google AutoSuggestions: 100%|███████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:27<00:00,  1.23term/s]
ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: 'charmap' codec can't encode characters in position 0-60: character maps to <undefined>


 📢❗🚨 Rising and Trending Keywords for ['mejores grupos ingleses']

🔝 Top: The most popular search topics.
🚀 Rising: Topics experiencing a significant increase in search frequency since the last time period. Topics marked :pile_of_poop:'Breakout' had a tremendous surge, likely because they are new and had few prior searches.
Empty DataFrame
Columns: []
Index: []
INFO|google_trends_researcher.py:488:save_in_file| Search content saved to C:\Flota\AI-Blog-Writer\workspace\web_research_reports\mejores_grupos_ingleses_2024-04-12_10-22-06
ERROR|google_trends_researcher.py:529:do_google_trends_analysis| Failed to get results from google trends related topics: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: 'charmap' codec can't encode characters in position 0-156: character maps to <undefined>
╒════╤═══════════════════════════════════╤═══════════════════════════════════════╤════════════════════════════════════════╤═════════════════════════════════╕
│    │ K📢eyword Col1                    │ K📢eyword Col2                        │ K📢eyword Col3                         │ K📢eyword Col4                  │
╞════╪═══════════════════════════════════╪═══════════════════════════════════════╪════════════════════════════════════════╪═════════════════════════════════╡
│  0 │ mejores grupos ingleses de los 80 │ los mejores grupos musicales ingleses │ nombres de los mejores grupos ingleses │ mejores grupos de rock ingleses │
├────┼───────────────────────────────────┼───────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────────────┤
│  1 │ mejores grupos ingleses actuales  │ grupos irlandeses                     │ grupos ingleses                        │ grupos ingleses de los 80       │
├────┼───────────────────────────────────┼───────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────────────┤

ERROR|main_text_generation.py:150:read_llm_parameters| An unexpected error occurred: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
ERROR|main_text_generation.py:55:llm_text_gen| Failed to read LLM parameters: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
ERROR|combine_blog_and_keywords.py:30:blog_with_keywords| blog_with_keywords: Failed to get response from LLM: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
ERROR|keywords_to_blog.py:76:write_blog_from_keywords| Failed to do Google Trends Analysis:'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
INFO|keywords_to_blog.py:77:write_blog_from_keywords| ########### Blog Content After Google Trends Analysis:#########



INFO|keywords_to_blog.py:85:write_blog_from_keywords| Pass Final blog for blog-proof reading and *improvements.
ERROR|main_text_generation.py:150:read_llm_parameters| An unexpected error occurred: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
ERROR|main_text_generation.py:55:llm_text_gen| Failed to read LLM parameters: 'charmap' codec can't decode byte 0x9d in position 2100: character maps to <undefined>
Failed to write blog on mejores grupos ingleses, Error: name 'logger' is not defined

**Comment by umesh070** [comment]
hi, @pixelatumente. 

@AJaySi has solved the issue. I have already tried the new code and it's working smoothly and gives better results. 

Please try the new code again.

**Comment by AJaySi** [comment]
@umesh070 Thanks a lot.
@pixelatumente  Please close the issue, if it works for you.

Regards.

**Comment by pixelatumente** [comment]
Great! Works fine! Thanks!
