### ISSUE TITLE
AI essay writer - Alwrity features

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Writer#35]
# AI Essay Writer - Alwrity feature 

### Essay Types
- **Argumentative**: Forming an opinion via research. Building an evidence-based argument.
- **Expository**: Knowledge of a topic. Communicating information clearly.
- **Narrative**: Creative language use. Presenting a compelling narrative.
- **Descriptive**: Creative language use. Describing sensory details.

### Education Levels
- **Primary School**
- **High School**
- **College**
- **Graduate School**

### Essay Type
Choose the type of essay you want to write from the options provided.

### Education Level
Select your current level of education from the given choices.

### Essay Title
Enter the title of your essay. The title should accurately reflect the content and focus of your essay.

### Number of Pages
Select the length of your essay by choosing one or more options:
- **Short Form (1-2 pages)**
- **Medium Form (3-5 pages)**
- **Long Form (6+ pages)**

**Comment by AJaySi** [comment]
You may try this in the latest code.
Few enhancements remaining, I will take them up when its being used widely.

**Comment by umesh070** [comment]
Essay writer is not working. The tool page is showing the error below.

ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/mount/src/alwrity-essay/essay_writer.py", line 4, in <module>
    import openai

Thank you for the help.

![Screenshot (24)](https://github.com/AJaySi/AI-Writer/assets/150319020/01b2e75d-53f0-4e8b-80a8-c0dfe2d2c565)
