### ISSUE TITLE
AI Essay writer tool is not working. 

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#37]
Essay writer tool is not working. The tool page is showing the error given below. Thank you for the help.

ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/mount/src/alwrity-essay/essay_writer.py", line 4, in <module>
    import openai

![Screenshot (24)](https://github.com/AJaySi/AI-Writer/assets/150319020/01b2e75d-53f0-4e8b-80a8-c0dfe2d2c565)

**Comment by AJaySi** [comment]
@umesh070 Please check again, I have fixed the issue.
If working, then close this issue. Thanks.
