### ISSUE TITLE
Regarding Issue Using Gemini API

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#39]
Hi, I am getting the following error while using the Gemini LLM model  API.

Thank you for your help.

![Screenshot (25)](https://github.com/AJaySi/AI-Writer/assets/150319020/1bb8986a-308d-45ad-99dc-de765fb18e32)

**Comment by AJaySi** [comment]
I had changed the retry logic, I will revert back to the original. This should be solved in next commit.

**Comment by pixelatumente** [comment]
I had the same error with Gemini. I solved it with a VPN

**Comment by DikshaDisciplines** [comment]
Hey @pixelatumente , could you share how did you use VPN as i am getting the similar error

**Comment by pixelatumente** [comment]
> Hey @pixelatumente , could you share how did you use VPN as i am getting the similar error

Before launching the script in Visual Studio Code with Gemini I activate a VPN such as WindScribe (free). Gemini Pro does not work in Europe by regulation

**Comment by AJaySi** [comment]
@umesh070 @pixelatumente @DikshaDisciplines 

Checkout/clone the latest code. Above issue is fixed. It was to do with Gemini API model version.
gemini-pro works but latest models give error like gemini-1.5-pro

Please help confirm and close this issue. Thank you.

**Comment by AJaySi** [comment]
@DikshaDisciplines 
Please check your GEMINI keys. You have provided wrong keys, henece API_KEY_INVALID.

**Comment by AJaySi** [comment]
@umesh070 
If working, please close this issue. We will use tickets for different issues. Thanks.

**Comment by umesh070** [comment]
I'm still encountering the same error using the Gemini API and running smoothly with the OpenAI API.

![Screenshot (78)](https://github.com/AJaySi/AI-Writer/assets/150319020/e9a4b166-caf0-48fa-a4e4-3b0d8e3b4aae)

**Comment by AJaySi** [comment]
Thanks @umesh070 .
I have updated the code, try:
`git pull`

**Comment by umesh070** [comment]
Gemini API is working smoothly now. 
Thank you for the help @AJaySi
