### ISSUE TITLE
Generate long posts

### ISSUE THREAD

**Issue by pixelatumente** [AJaySi/AI-Writer#40]
There is a way to generate long articles?
Even if I change the number of tokens, the posts are about 500 words. (GPT or Gemini Pro)

I used on main_config:
model = gpt-3.5-turbo-16k
max_tokens = 8192

Thanks!

**Comment by AJaySi** [comment]
Hello,

I recently closed this one : https://github.com/AJaySi/AI-Writer/issues/34

Can you please elaborate on:
1). How long is your content ?
2). What type of content are you planning to write ?

**Comment by pixelatumente** [comment]
I write in Spanish as I am from Barcelona. The article below is a sampling of the length I get finally. They are topics related to museums

---
title: Discovering the Artistic Treasures of Museo del Prado
date: 2024-03-16 02:06:51 +0530
categories: [Travel, Art and Culture]
tags: [arte, museo del prado]
description: Explore the artistic beauty of Museo del Prado in Madrid. Uncover its unique charm and cultural significance as a world-renowned art museum. Dive into its fascinating history and key aspects that make it a must-visit for art lovers.
img_path: '/assets/'
image:
    path: generated_image_2024-04-17-17-57-39.png
    alt: Discovering the Artistic Treasures of Museo del Prado
---

Explora la belleza artística del Museo del Prado en Madrid

Introducción Descubre la belleza única y la importancia cultural del Museo del Prado, un museo de arte reconocido a nivel mundial ubicado en el corazón de Madrid. Vamos a adentrarnos en su fascinante historia y explorar algunos aspectos clave que hacen de esta institución una visita obligada para los amantes del arte.

Aspectos Clave sobre el Museo del Prado El Museo del Prado se destaca como un punto destacado del arte europeo, albergando una colección impresionante que abarca siglos. Desde pinturas excepcionales hasta esculturas detalladas, este museo es un lugar especial para aquellos que buscan inspiración artística y conocimiento histórico.

Preguntas Frecuentes

¿Cuándo puedo visitar el Museo del Prado sin costo?

Aprovecha la entrada libre en días seleccionados como los miércoles, Día Internacional de los Museos (18 de mayo), Día Nacional (12 de octubre) y Día de la Constitución (6 de diciembre). Además, ciertos grupos como familias numerosas y menores pueden disfrutar de entrada gratuita.
¿Cuál es la obra más destacada en el Museo del Prado?

Entre las posesiones más valiosas se encuentra "Degollación de San Juan Bautista y banquete Herodes" por Bartholomäus Strobel el Joven, venerada por su brillantez artística.
¿Cuánto tiempo se necesita para explorar todo El Prado?

Para una experiencia curada centrada alrededor aproximadamente 30 obras maestras, los visitantes pueden recorrer el museu en aproximadamente dos horas, saboreando cada pieza con profundidad y aprecio.
¿Cuáles son las tarifas para entrar a El Prado?

Los precios típicos varían desde €15 para adultos hasta €7.50 para personas mayores mayores 65 años. Niños y estudiantes entre 18-25 años tienen entrada gratuita a esta joya cultural.
Información sobre Experiencia Virtual Embárcate en un tour virtual inmersivo por la cautivadora colección através sde su página web [aquí](https://www.museodelprada.es/). Explora obras icónicas desde tu hogar mientras absorbesla belleza e historia que esta estimable institución tiene para ofrecer.

Conclusión Prepárate para un viaje enriquecedor a travésdel tiempo y arte visitando armad con conocimientos obtenidos dse estas Preguntas frecuentes Ya seaque optes por explor sus salones físicamente o virtualmente, prepáratepara ser cautivadoporlas maravillasartísticasque te esperan dentro desta joya culturalen Madrid. Referencias: 1.[Sitio web oficial turismo - Turismo Madrid](https://www.esmadrid.com/en/tourist-information/museodelprado) 2.[Visita - Sitio web oficial](https://www.museodelprada.es/en/visit-the-museum/) 3.[Informacióndela Colección](https://www.museodelprada.es/en/the-collection/)'.'

**Comment by AJaySi** [comment]
AI blog writer is limited in content output(500-1000 words).
I will spend sometime on this and improve it. 

1). How is the spanish output of alwrity, does it use difficult, unnatural words ?
2). What considerations should alwrity have spanish language ?

**Comment by pixelatumente** [comment]
I basically use longtail keywords and not more than one at a time. In Spanish sometimes the result is shown in English or while running the script it alternates Spanish with English. The utf-8 format is important.

**Comment by AJaySi** [comment]
1). Making changes for utf-8 already. All file operations are compliant.
There are few more problems with cross platform compatibility. I will soon address them.

2). Working on giving option for short-form and long-form content for AI writers.

**Comment by AJaySi** [comment]
@pixelatumente  @DikshaDisciplines 
I have include code for long form content with keyword to blog.
