### ISSUE TITLE
NameError: name 'radiolistbox' is not defined

### ISSUE THREAD

**Issue by grapefruitgreentealoe** [AJaySi/AI-Writer#45]
after i command 
```
!python alwrity.py
```

this error occurs
```
NameError: name 'radiolistbox' is not defined
```

**Comment by umesh070** [comment]
Hi, @grapefruitgreentealoe  It seems there's a slight error in the command syntax. Instead of using **!python alwrity.py**, try using **python alwrity.py**. Please give it a try and let us know if the error persists. Feel free to share a screenshot if you encounter any further issues. Thank you.

**Comment by umesh070** [comment]
hi, @grapefruitgreentealoe  
Even I am getting the same error while using gemini API. 
Try openai API. You will not get the error with openai API.

**Comment by umesh070** [comment]
@grapefruitgreentealoe  
It was to do with Gemini API model version.
gemini-pro works but latest models give error like gemini-1.5-pro

**Comment by grapefruitgreentealoe** [comment]
@umesh070 thanks for answering me! ❤️

**Comment by umesh070** [comment]
You are welcome @grapefruitgreentealoe 

Please close this issue. If it's working for you. 👍
