### ISSUE TITLE
ERROR save_blog_to_file

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#46]
Hi AJ,
i am unable to save the blog to file. kindly help

![image](https://github.com/AJaySi/AI-Writer/assets/158307974/a4002d3e-3107-46df-931f-e52139eb9d53)

**Comment by AJaySi** [comment]
@DikshaDisciplines 
I have fixed this issue in latest code. `git pull`
Thanks.
