### ISSUE TITLE
Error While Generating Long Form Blog Content

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#48]
I tried to generate a long-form blog article but encountered an error mentioned below. Thank you for your help.

![Screenshot (79)](https://github.com/AJaySi/AI-Writer/assets/150319020/265b3568-3a49-472f-aaa1-b9a7529ca5e3)

**Comment by pixelatumente** [comment]
I get these errors when I create a long article
![error](https://github.com/AJaySi/AI-Writer/assets/115550520/92169075-b783-4378-91bd-77776aba4dbd)

**Comment by AJaySi** [comment]
@pixelatumente 
At present, this is Gemini API only. Openai is not supported as yet.
Try with Gemini Api.

Your 'compute engine.. winerror' is mostly to do with GCP.

**Comment by AJaySi** [comment]
@umesh070 
Please share a larger screenshot. Its a windows problem, yet again.

**Comment by umesh070** [comment]
I'm still encountering the same error when trying to create longer content. It seems to pop up right after tool research on the SERP web. I've included a screenshot of the error below for reference.

![Screenshot (80)](https://github.com/AJaySi/AI-Writer/assets/150319020/6c7d7d79-a27f-400e-82be-e24ffba86932)

**Comment by umesh070** [comment]
PS C:\WINDOWS\system32\AI-Writer> pip show google.generativeai
Name: google-generativeai
Version: 0.3.2
Summary: Google Generative AI High level API client library and tools.
Home-page: https://github.com/google/generative-ai-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: C:\Users\this\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: google-ai-generativelanguage, google-api-core, google-auth, protobuf, tqdm, typing-extensions
Required-by:
PS C:\WINDOWS\system32\AI-Writer>

**Comment by AJaySi** [comment]
@umesh070 
Yup, update your google.generativeai to latest.

**Comment by umesh070** [comment]
Thank you @AJaySi for your assistance! With your help, I'm now able to produce high-quality, lengthy blog content. Your work is truly incredible.

However, I've noticed that the tool is overdoing it a bit. It's repeatedly generating the last 50% of the blog content three times in a row.

**Comment by AJaySi** [comment]
Thanks a lot @umesh070 

1). I will work on removing the repetitions today.

**Comment by AJaySi** [comment]
@umesh070 
I am closing this issue, as specifically its done.

OPen a new issues for:
"However, I've noticed that the tool is overdoing it a bit. It's repeatedly generating the last 50% of the blog content three times in a row."
