### ISSUE TITLE
Requesting Adding Google Ads Generator, Letter Writer, and Email Writer to Alwrity's Features 

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#49]
-

**Comment by AJaySi** [comment]
What is Ads generator ?

**Comment by umesh070** [comment]
Google Ads content generator.

**Comment by AJaySi** [comment]
Email writers are included. I will push the cli code soon.

**Comment by AJaySi** [comment]
Google Ads descriptions and letter writers are done.
I will push code for CLI.
