### ISSUE TITLE
Keyword Web Research Issue

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#53]
Keyword web research is not working. I am getting the below error message.

![Screenshot (87)](https://github.com/AJaySi/AI-Writer/assets/150319020/e44af7f2-2476-45b4-a0da-2a2b147727f0)

**Comment by AJaySi** [comment]
I have fixed this issue. Please confirm and close.
Note: requirements file has changed. Do: 
`git pull`
`pip install -r requirements.txt`

**Comment by umesh070** [comment]
I did the git pull and install requirements.txt

now I am getting the following error

![Screenshot (89)](https://github.com/AJaySi/AI-Writer/assets/150319020/765dfc9c-867f-4bca-8cbf-eceef6a16a3c)

**Comment by AJaySi** [comment]
Oops

**Comment by AJaySi** [comment]
Updated requirements.txt
