### ISSUE TITLE
AI agent 

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#65]
1.  Under  Working Agent mention - Agent Content Team identity like researcher, outliner, writer, reviewer 

![image](https://github.com/AJaySi/AI-Writer/assets/158307974/fe458d66-adbe-4445-a668-8ab0cf726b46)

2. If Below error, then Aborted search with message.
![image](https://github.com/AJaySi/AI-Writer/assets/158307974/7b42205d-24e4-4ae7-bd1c-e5b23958b402)

**Comment by AJaySi** [comment]
@DikshaDisciplines 
Great, you are trying the agents team.
The error is with Crewai which fails to do google search result.
Does the error come everytime, with every run ?

I will try to improve this at Alwrity.com

**Comment by DikshaDisciplines** [comment]
yes JJ the error still occurs

**Comment by AJaySi** [comment]
@DikshaDisciplines 
This is CrewAI problem as below : https://github.com/joaomdmoura/crewAI/issues/430

I have updated the code and it *should work. (Hahahaha) It should work most of the times now.
If its troubling you, I try a more permanent fix.

**Comment by AJaySi** [comment]
@DikshaDisciplines 

No confirmations, cant wait, so closing it.
