### ISSUE TITLE
Waiting sign/msg/symbol after the initial prompt    python .\alwrity.py

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#66]
![image](https://github.com/AJaySi/AI-Writer/assets/158307974/bbb11f80-3d1c-4858-9579-12b3261784cd)

**Comment by AJaySi** [comment]
For now, I have put messages and closing it.

Note : The bigger issue being alwrity taking so much startup time.
In recent future, I will revisit and address the slow starting up.
