### ISSUE TITLE
Text Rewording 

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#68]
REWRITE TEXT ABOUT ANY TOPIC

**Comment by AJaySi** [comment]
@DikshaDisciplines 
What does that even mean ?
Please elaborate.

**Comment by DikshaDisciplines** [comment]
User can use AI to instantly rewrite content for essays, articles, emails, and beyond
Same content, new text! If you already have a specific piece of content that you would like to re-publish, we got you covered. Submit it, wait for two minutes, and tada. Your article is reworded.

MAKE THE MOST OUT OF YOUR CONTENT
REWRITE TEXT ABOUT ANY TOPIC

**Comment by AJaySi** [comment]
Understood. I will work on this soon.

**Comment by AJaySi** [comment]
The new UI will have a "Talk to your documents" feature for content creation.
