### ISSUE TITLE
TBDs & Alwrity tools to implement - Roadmap

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Writer#71]
@DikshaDisciplines 

AI Assets to be created  (Priority list)
1. AI Ad ( advertisement) Creator : For Advertising industry 
- for all digital platforms like Social media, Youtube, Twitter, Linkedin and Website page.
2. Human in loop AI Application : For freelancers 
- Domain authority
3. PDFs information application  : For FAQ and Research/thesis industry 
4. AI Social Applications : For Digital Marketing industry 
  - All digital platform like Social media, Youtube, Twitter, Linkedin marketing tool
5. AI Organization builder : For SMBs and freelancers
- Business plan/structure/departments/Business calendar.. so on 
hashtag
6. AI FinTech Applications 
- Financial News writer
- Technical Analysis (stock market)
7. [AICourse](https://www.linkedin.com/feed/hashtag/?keywords=aiwritercourse&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A7196800286865154049)Writer : for Education industry

**Comment by AJaySi** [comment]
Done: 
AI Facebook post writer  -  https://alwrity-facebook.streamlit.app/

**Comment by AJaySi** [comment]
@umesh070 
Done: https://alwrity-tweets.streamlit.app/

**Comment by DikshaDisciplines** [comment]
+
8. Content calendar feature to website 
9. AIEducation - covering  AIBookWriter and AICourseWriter

**Comment by AJaySi** [comment]
YT script generator : https://alwrity-ytscript.streamlit.app/

**Comment by AJaySi** [comment]
Youtube Description writer : https://alwrity-yt-description.streamlit.app/

**Comment by DikshaDisciplines** [comment]
12.  Recycle AI data :  Save and Reuse data like Domain authority website links (Parameters TBD) and Domain authority Article/Topics links (trendy topics - Parameters TBD) under AI Assets :
- AI Brain 
- AI Content Planner
- Ask Alwrity
#AIRecycle

**Comment by AJaySi** [comment]
Taken care of most of the features asked above.
Present focus is UI and porting functions to it.
