### ISSUE TITLE
Alwrity AI apps update

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Writer#72]
@umesh070  is working on the following: (Update here)

Done
1. Site is now optimised for mobile.
2. Contrast test done with a warm background color on the website scored more than the white background.
3. Facebook and Twitter tools added to the website.

Have to be done
1. Tool icon change.
2. Toolbox and content improvement.
3. Add content section-wise and section SEO.
4. Have to work on-site speed.
5. Make last month's analytics report.

I have tested site speed insight we have to work more on site speed. Reports are attached below.

**Comment by AJaySi** [comment]
@umesh070 
If you have made any progress, do update here. Thanks.

**Comment by umesh070** [comment]
Work on progress.

1. The tool icon changed.
2. Toolbox and content improvement.
3. Add content section-wise and section SEO.
4. Last week we updated 10 pages and 2 blogs. Visitors increased by double on 2 pages. 

[https://docs.google.com/spreadsheets/d/1hjQoc1otDA77Bgv7IwXcaUiN7GfAe97xvikdBNJWiXI/edit#gid=0]

**Comment by AJaySi** [comment]
@umesh070  Great, Thanks.

**Comment by AJaySi** [comment]
@umesh070 
Should I close this, if all items are done ?

**Comment by umesh070** [comment]
@AJaySi 
Yes, all these items are done.
