### ISSUE TITLE
UI Target Audience

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#77]
Target Audience (Final list)
- Gen-Z
- AI Expert
- SEO
- Digital Marketing
- Student
- Tech-savvy
- Professional
- Customize (Content creator, Financial expert, etc)

![image](https://github.com/AJaySi/AI-Writer/assets/158307974/510dd99e-3581-40ae-b7a7-067f98516401)

**Comment by AJaySi** [comment]
@DikshaDisciplines 

Done. Please check with latest code, git pull.
Please close this ticket, if meets your requirement.

**Comment by DikshaDisciplines** [comment]
Under 

1. Target Audience - Update as per below sequence 
- Professional
- Gen-Z
- Texh-savvy
- Student (singular)
- Digital Marketing
- AI Expert
- Replace 'Other' with 'Customize' (Eg. Domain expert, Content creator, Financial expert :  These name should reflect)

![image](https://github.com/AJaySi/AI-Writer/assets/158307974/0e73fbe4-8c52-48ab-b20e-5ed00b5484d7)

2. UI Guide (how to use the application/tabs) for first time uses.

**Comment by AJaySi** [comment]
@DikshaDisciplines 
I have updated point 1, in the latest commit. Please check.

For point 2, its better to have a separate ticket, which will be of priority for now.

**Comment by DikshaDisciplines** [comment]
pls remove Domain expert
