### ISSUE TITLE
Alwrity error

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#80]
I am getting the below error while running Alwrity in local. Thank you for your help.

![Screenshot (146)](https://github.com/AJaySi/AI-Writer/assets/150319020/b471db82-e3da-4df5-9777-41be6f25d5bc)

**Comment by AJaySi** [comment]
pip install -r requirements.txt

**Comment by umesh070** [comment]
This error is coming after the pip install -r requirements.txt

**Comment by AJaySi** [comment]
Updated code, Try again.
Close it after verification.

**Comment by umesh070** [comment]
The issue is solved thank you.
