### ISSUE TITLE
UI Enhancement 

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#81]
1.  Content Language
I chose 'Nepali' under Content Language but no content was generated. (attached is screen short)

2. Image Generator
Image not getting generated. (attached is screen short)

3. Long form content Generator 
Getting error in generating content for some topics.

4. Content Language
'Option' to be included in dropdown, similar to "Enter your target audience", so that writer can chose other languages.

5. Normal form content Generator 
Could we get two drafts of content generated like before.

![Screenshot 2024-06-14 184004](https://github.com/AJaySi/AI-Writer/assets/158307974/bbe68ab4-0255-4af6-b5d0-45cd6d9b6a89)

**Comment by AJaySi** [comment]
1). Fixed : Content Language
2). Fixed : Image Generator
3). Fixed : Image Generator
4). Fixed : 

5). Long form content Generator : Working on it, but will open a new issue for it.

@DikshaDisciplines : Try splitting issues into multiple tickets. 
Many of these issues are not related and should have their own tickets. Many of the issues are not trivial.
Multiple tickets help in documentation too.
We should stick to one issue per ticket. Thanks.
