### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#82]
1. Add Audio (mike symbol) feature under Blog Content Writer

add mike symbol before the question symbol
<img width="389" alt="image" src="https://github.com/AJaySi/AI-Writer/assets/158307974/15a54831-ae22-40a4-b460-ddd9cc04d66b">

2. Add COPY (symbol and text) for copying the draft 1 and draft 2.
3.  next to it add Audio (mike symbol) feature - so that the writer can listen to the blog draft 1 and draft 2
<img width="682" alt="image" src="https://github.com/AJaySi/AI-Writer/assets/158307974/91d681e2-23a6-4fdf-aeab-2fda24147e54">

**Comment by AJaySi** [comment]
Looking into it. Thanks for the screenshots.

**Comment by AJaySi** [comment]
@DikshaDisciplines 

I have added an audio button to speak out keywords(Speech to text)
Added button to read out the final blog draft. 

This is great resources to build tools for podcast : https://elevenlabs.io/
