### ISSUE TITLE
Draft 2 not generated 

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#84]
🚫 Failed to write blog on How to Write Blog Introductions That Hook Readers, Error: 'NoneType' object has no attribute 'replace'

![image](https://github.com/AJaySi/AI-Writer/assets/158307974/cde157fd-9cba-4982-94d9-06469d82b402)

**Comment by AJaySi** [comment]
@DikshaDisciplines 

Thanks. Alwrity is broken for now. I have put the commit status WIP - Work in Progress.
I will solve this today and other issues as well.

Regards.

**Comment by AJaySi** [comment]
Draft 2 of the content should be displayed even when image generation fails.
Closing.
