### ISSUE TITLE
UI - Error for German language AI generation

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#85]
Kindly fins attached data generation errors for German language 

![Uploading 1.jpg…]()

**Comment by AJaySi** [comment]
@DikshaDisciplines 
1). German language selected while providing web url works fine.

2). I will check keywords & confirm.

**Comment by AJaySi** [comment]
2). Works for german language too. Closing for now.
@DikshaDisciplines Feel free to open if the issue persists.
