### ISSUE TITLE
Addition of data representation in the form of graphs, pie charts, etc in the article draft

### ISSUE THREAD

**Issue by DikshaDisciplines** [AJaySi/AI-Writer#88]
Addition of data representation in the form of graphs, pie charts, etc in the article draft

**Comment by AJaySi** [comment]
Alwrity with streamlit is quite capable of representing graphs and pie charts.
Finance and research type articles will benefit from it.
Data in tabular form gets rendered for now.

Havent written an article with lot of data. Request you to give me an example of the same. 
Dev Team will then try to present such information.

Thanks.

**Comment by AJaySi** [comment]
@DikshaDisciplines 
We will handle all of the above requirements in the New UI, as per your designs.
