### ISSUE TITLE
Problem with the Story Writer Tool

### ISSUE THREAD

**Issue by 72Joe72** [AJaySi/AI-Writer#92]
Hello,
I'm an absolute beginner in the IA world and wanted to test this story writing tool. but after entering the settings an klick the generate button I get the following error in the web interface:

Premise Generation Error: 'str' object has no attribute 'text'

💥 Failed to generate Story. Please try again!

The console says the following:
Error generating content: 400 User location is not supported for the API use without a billing account linked.

Do I need a paid API? If so, which ones ? or is this another error

**Comment by AJaySi** [comment]
Hey Joe,

Hope you are doing great. Thank you for the details in the issue.

1). Your error does suggest you need a paid API.  It also indicates that your specific geo-location requires a paid API.

2). Gemini API is free and works mostly for all.  OpenAI is getting greedy.

3).  You can try this too: https://www.alwrity.com/ai-story-writer
Note: Also, using VPN, going incognito also helps.

4). Alwrity works with OpenAI, Google, Anthropic AI models. You can choose the ones that suits your budget. 
Let us know your specific requirements and we will guide you further. 

Thank you for trying out Alwrity. Have a great day. Regards.

**Comment by AJaySi** [comment]
@72Joe72 :
 As its Not an Alwrity Bug, closing the issue.
